#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        int1: '8096'
        ext1: '8096'
        image: 'emby/embyserver'

    # CORE (MANDATORY) ############################################################
    - name: 'Mandatory Core Role'
      include_tasks: '/pg/apps/_core.yml'

    - name: 'XML Check'
      stat:
        path: /pg/data/{{pgrole}}/config/system.xml
      register: xmlcheck

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.enable: 'true'
          traefik.port: '{{int1}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain}},{{tldset}}'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - /etc/localtime:/etc/localtime:ro
          - /pg/data/{{pgrole}}:/config
          - '{{path.stdout}}:{{path.stdout}}'
          - '/mnt:/mnt'
          - '/pg/unity:/unity'
          - '/pg:/pg'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          UID: '1000'
          GID: '1000'
          GIDLIST: '1000'

    # MAIN DEPLOYMENT #############################################################
    - name: "Check"
      stat:
        path: "/dev/dri"
      register: dev_dri

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{serverports}}{{ext1}}:{{int1}}'
        devices: "{{ '/dev/dri:/dev/dri' if dev_dri.stat.exists == True | default(false) else omit }}"
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        expose: '8096'
        state: started
        labels: '{{pg_labels}}'

    # FIRST TIME CONFIGURATION ###########################################################
    - name: 'Configuring {{pgrole}} for first time use'
      block:

      - name: 'Pending XML Generation'
        wait_for:
          path: '/pg/data/{{pgrole}}/config/system.xml'
          state: present

      - name: 'Wait 5 Seconds'
        wait_for:
          timeout: 5

      - name: 'Stop {{pgrole}}'
        docker_container:
          name: '{{pgrole}}'
          state: stopped

      - name: 'Turn Off Reporting'
        xml:
          path: '/pg/data/{{pgrole}}/config/system.xml'
          xpath: /ServerConfiguration/EnableAnonymousUsageReporting
          value: 'false'

      - name: 'Restart {{pgrole}}'
        docker_container:
          name: '{{pgrole}}'
          state: started
      when: not xmlcheck.stat.exists
