#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Pull Stored Data
      shell: 'cat /pg/tmp/watchtower.set'
      register: programs

    - name: Deploy watchtower
      docker_container:
        name: 'watchtower'
        image: 'containrrr/watchtower'
        pull: yes
        command: '{{programs.stdout}} --cleanup --interval 600'
        #cpu_shares: 64
        state: started
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /etc/localtime:/etc/localtime:ro
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - 'watchtower'
