#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- name: 'Deploying {{pgrole}}'
  docker_container:
    name: '{{pgrole}}'
    image: '{{imageselect.stdout}}'
    pull: yes
    published_ports:
      - '{{ext1}}:{{int1}}'
      - '{{portinfo}}{{ext2}}:{{int2}}'
      - '{{portinfo}}{{ext3}}:{{int3}}'
      - '{{portinfo}}{{ext4}}:{{int4}}'
      - '{{portinfo}}{{ext5}}:{{int5}}'
      - '{{portinfo}}{{ext6}}:{{int6}}'
      - '{{portinfo}}{{ext7}}:{{int7}}'
      - '{{portinfo}}{{ext8}}:{{int8}}'
      - '{{portinfo}}{{ext9}}:{{int9}}'
      - '{{portinfo}}{{ext10}}:{{int10}}'
      - '{{portinfo}}{{ext11}}:{{int11}}'
    volumes: '{{pg_volumes}}'
    devices: "{{ '/dev/dri:/dev/dri' if dev_dri.stat.exists == True | default(false) else omit }}"
    etc_hosts:
      { 'analytics.plex.tv': '127.0.0.1', 'metrics.plex.tv': '127.0.0.1' }
    env:
      PLEX_UID: '1000'
      PLEX_GID: '1000'
      ADVERTISE_IP: '{{customConnections}}'
    networks:
      - name: plexguide
        aliases:
          - '{{pgrole}}'
    restart_policy: unless-stopped
    state: started
    labels: '{{pg_labels}}'
